title: Breon Feran
logo_title: "Breon<br/>Feran"
email: breon.feran@gmail.com
logo: /assets/img/breon.png
description: >-
  Welcome to my profile website!
  Here you can find some of the projects I've done and ones I'm currently working on.
baseurl: ""
url: ""
github_username:  bferan
show_downloads: false

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
